

stages:
    - build

docker-build:
    only:
      - master
    image: docker:latest
    stage: build
    services:
      - docker:dind
    before_script:
      - docker login --username rezaqanbari --password f24b50e9-331d-493d-9a8a-e2f4b9fca8bf
    script:
      - docker build --pull -t rezaqanbari/loghmeh .
      - docker push rezaqanbari/loghmeh
  