apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sql-db
spec:
  selector:
    matchLabels:
      app: my-sql-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-sql-db
    spec:
      containers:
      - name: my-sql-db
        image: mysql:8.0.19
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "12345"
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        resources:
          limits:
            memory: "400Mi"
            cpu: "250m"
        ports:
        - containerPort: 3306
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
        