apiVersion: apps/v1
kind: Deployment
metadata:
  name: loghmeh-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: loghmeh-backend
  template:
    metadata:
      labels:
        app: loghmeh-backend
    spec:
      containers:
      - name: loghmeh-backend
        image: rezaqanbari/loghmeh
        env:
        - name: JVM_OPTS
          value: "-XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -XX:MaxRAMFraction=1 -Xms500M"
        resources:
          limits:
            memory: "500Mi"
            cpu: "400m"
        ports:
        - containerPort: 8080
