apiVersion: v1
kind: Service
metadata:
  name: loghmeh-backend-service
spec:
  selector:
    app: loghmeh-backend
  type: LoadBalancer
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 31037
